#!/usr/bin/env node
// Fetches the RTC Sheets endpoint (one Google Sheet, four tabs, one Apps
// Script Web App), validates the payload, and regenerates js/data/*.js in
// place. Run by .github/workflows/sync-data.yml — never call this endpoint
// from the browser, the site is static and data is frozen at build time.

import { writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ENDPOINT = process.env.RTC_SHEET_ENDPOINT;
const ATTEMPTS = 3;
const TIMEOUT_MS = 20000;
const RETRY_DELAY_MS = 5000;
const REQUIRED_SECTIONS = ["casebooks", "individual", "mbb", "cotw"];
const NON_EMPTY_SECTIONS = ["casebooks", "individual", "mbb"]; // cotw may legitimately be empty/null

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const DATA_DIR = path.join(__dirname, "..", "js", "data");

function sleep(ms) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

function fail(message) {
  console.error(`sync-data: ${message}`);
  process.exit(1);
}

async function fetchWithRetry(url) {
  let lastErr;
  for (let attempt = 1; attempt <= ATTEMPTS; attempt++) {
    const controller = new AbortController();
    const timer = setTimeout(() => controller.abort(), TIMEOUT_MS);
    try {
      const res = await fetch(url, { signal: controller.signal });
      clearTimeout(timer);
      return await res.text();
    } catch (err) {
      clearTimeout(timer);
      lastErr = err;
      console.warn(`sync-data: attempt ${attempt}/${ATTEMPTS} failed (${err.message})`);
      if (attempt < ATTEMPTS) await sleep(RETRY_DELAY_MS);
    }
  }
  throw lastErr;
}

// Matches the export shape of the existing js/data/*.js files exactly —
// same const names, same getX() function names, same Promise.resolve
// pattern — so no other file in the site needs to change.
function jsFile(sourceComment, varName, value, fnName) {
  return `// AUTO-GENERATED by .github/workflows/sync-data.yml — do not edit by hand.
// ${sourceComment}
const ${varName} = ${JSON.stringify(value, null, 2)};

function ${fnName}() {
  return Promise.resolve(${varName});
}
`;
}

async function main() {
  if (!ENDPOINT) fail("RTC_SHEET_ENDPOINT is not set.");

  let raw;
  try {
    raw = await fetchWithRetry(ENDPOINT);
  } catch (err) {
    fail(`could not reach the endpoint after ${ATTEMPTS} attempts: ${err.message}`);
    return;
  }

  let payload;
  try {
    payload = JSON.parse(raw);
  } catch {
    fail("response was not valid JSON.");
    return;
  }

  if (payload.error) {
    fail(`endpoint returned an error: ${payload.error}`);
    return;
  }

  const sections = payload.sections;
  if (!sections) fail('response is missing "sections".');

  for (const key of REQUIRED_SECTIONS) {
    if (sections[key] === null || sections[key] === undefined) {
      fail(`section "${key}" is null/missing.`);
    }
  }

  for (const key of NON_EMPTY_SECTIONS) {
    if (!sections[key].count) {
      fail(`section "${key}" has count 0 — refusing to overwrite good data with an empty section.`);
    }
  }

  const warnings = payload.warnings || [];
  if (warnings.length) {
    console.log(`sync-data: ${warnings.length} warning(s) from the sheet:`);
    warnings.forEach((w) => console.log(`  - ${w}`));
  } else {
    console.log("sync-data: no warnings from the sheet.");
  }

  const files = {
    "casebooks.js": jsFile(
      "Source: RTC Sheet, \"Casebooks\" tab. University colors are NOT part of this file — see university-colors.js.",
      "CASEBOOKS",
      sections.casebooks.items,
      "getCasebooks"
    ),
    "individual-cases.js": jsFile(
      'Source: RTC Sheet, "Individual Cases" tab.',
      "INDIVIDUAL_CASES",
      sections.individual.items,
      "getIndividualCases"
    ),
    "mbb-links.js": jsFile(
      'Source: RTC Sheet, "MBB Cases" tab.',
      "MBB_LINKS",
      sections.mbb.items,
      "getMbbLinks"
    ),
    "case-of-week.js": jsFile(
      'Source: RTC Sheet, "Case of the Week" tab. `current` can legitimately be null (no pick active yet) — render-home.js hides the notification bar when it is.',
      "CASE_OF_WEEK_STATIC",
      sections.cotw.current,
      "getCaseOfWeek"
    )
  };

  for (const [name, content] of Object.entries(files)) {
    await writeFile(path.join(DATA_DIR, name), content, "utf8");
  }

  console.log("sync-data: wrote js/data/{casebooks,individual-cases,mbb-links,case-of-week}.js");
}

main();
